### ISSUE TITLE
Toolbar fails to open

### ISSUE THREAD

**Issue by mh-anwar** [mh-anwar/CopyThat#42]
**Describe the bug**
The toolbar will not open from the popup on any page

**Expected behavior**
The toolbar should have opened or appeared

**Error Message**
```
content.js:66 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'addEventListener')
    at toolbar_select_form_populator (content.js:66:5)
    at content.js:26:7
```

- Device: Chromebook
- OS: ChromeOS
- Browser: Chrome

**Comment by mh-anwar** [comment]
Issue fixed, toolbar now opens and closes from Popup
